# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d145af19670f7a464afdf5aa9bf1fd730b5f5749150029f436c69e9d92a5a3ae660383ab702fd198c87a00c815b2e48f29d68f74e68cab47795a0e3f5cb06e1

test:
  secret_key_base: 14659f707bbbd8b040fb5fa2fb996f519a1ce89fe393decc35463549a9bb2c18cfefcb575c123dc5a9afca8c0f5304986673a578e8d1cc178854ea9f10d27f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
